service: reto-lambda-serverless-bolvera
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:492804555841:table/planet_table
        - arn:aws:dynamodb:us-west-2:492804555841:table/specie_table

functions:
  
  getPlanet:
    handler: src/public/api/v1/getPlanetApi.getPlanetApi
    events:
      - httpApi:
          path: /api/v1/planet/{id}
          method: get

  getSpecie :
    handler: src/public/api/v1/getSpeciesApi.getSpecies
    events:
      - httpApi:
          path: /api/v1/specie/{id}
          method: get

  saveSpecie:
    handler: src/public/api/v1/createSpecieApi.createSpecie
    events:
      - httpApi:
          path: /api/v1/specie
          method: post

  getAllSpecies :
    handler: src/public/api/v1/getAllSpeciesApi.getAllSpecies
    description: Listar todas las "Species"
    events:
      - httpApi:
          path: /api/v1/species-all
          method: get

  generateSwagger:
    handler: src/public/documentation/swagger.handler
    description: Generate Swagger documentation
    events:
      - http:
          path: /api/documentation
          method: get


resources:
  Resources:

    PlanetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: planet_table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    SpecieTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: specie_table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline

custom:
  swagger:
    documentationEndpoint: api/documentation
    swaggerDefinitionFile: src/public/documentation/swagger-definition.yaml